### PR TITLE
Issue #24: Create a unit test for the jenkins load simulator python script

### LINKED ISSUE #24: Create a unit test for the jenkins load simulator python script
FEATURE REQUEST

What happened:

The jenkins load simulator python script needs a unit-test to be created (Refer: https://github.com/openebs/test-tools/blob/master/jenkins-client/jenkins-load-simulator.py)

Anything else we need to know?:

References :
https://stackoverflow.com/questions/652292/what-is-unit-testing-and-how-do-you-do-it
http://pythontesting.net/framework/unittest/unittest-introduction/

### PR DESCRIPTION
**Pull request by andrewnester**
**What this PR does / why we need it**:
Added missing unit test for jenkins load simulator

**Which issue this PR fixes** 
Fixes #24

### CODE REVIEW

**Comment by harshvkarn** [comment]
@andrewnester Thanks for the Pull request, can you please attach the output of the test run?

**Comment by andrewnester** [comment]
@harshvkarn Right now the test output is like the one below

```
python3 test-jenkins-load-simulator.py 
<MagicMock name='mock.jobs_count()' id='140520927771392'>
<MagicMock name='mock.get_jobs()' id='140520927812800'>
<MagicMock name='mock.get_job_config()' id='140520927653504'>
<MagicMock name='mock.get_jobs()' id='140520927812800'>
<MagicMock name='mock.jobs_count()' id='140520927771392'>
.
----------------------------------------------------------------------
Ran 1 test in 8.014s

OK
```

It could be changed to return some mocked response but I don't see a lot of value doing this. What do you think?

**Comment by andrewnester** [comment]
@harshvkarn @shashank855 any feedback on the CR? :) Thanks!

**Comment by ksatchit** [comment]
Thanks for the PR @andrewnester !! Do star the repo if you felt it serves a useful purpose!

**Pull request merged**
